// lib/curriculum/episodes.ts
// RideWitUS — 32-episode podcast curriculum, BVC-format. Bike progression by season:
//   • Season 1 (Apron Foundations) — single-speed cruiser. The simplest bike at
//     the donation bay. No derailleur, no shift cable, no cassette to fight.
//   • Season 2 (Apron Advanced) — bikes with gears. Cassettes, freewheels,
//     derailleurs, internal hubs (Sturmey-Archer, Shimano Nexus). The gears chapter.
//   • Season 3 (Bike Design & Folding-Bike Engineering) — the Brompton enters as
//     the engineering object lesson.
//   • Season 4 (Program Operations & Community) — bike-agnostic.
// A future "v2" of S1 may re-record on a multi-gear bike for listeners who want
// the same foundational skills with a shifting context already in place.
// Source of truth for the catalog, RSS feed, season pages, and episode landing
// pages. Bodies are placeholders; production scripts live in ./plans/curriculum/.
// Update episode entries (status, audioUrl, transcriptUrl, academyLessonId,
// flashlearnSetId, wanderlearnTourId) as each episode ships.

import type { Episode } from "@/types/episode";

export const EPISODES: Episode[] = [
  // ---- Season 1 — Apron Foundations (Green + Red) -----------------------------
  {
    id: 1,
    season: 1,
    ep: 1,
    slug: "tools-stand-and-safety-culture",
    title: "Tools, Stand, & Safety Culture",
    subtitle: "The apron itself, and what a classroom of wrenches feels like.",
    apronLevel: "green",
    body: "Every shop has a rhythm. We open the curriculum with the apron, the stand, and the first ten tools that will teach you what your hands are doing — taught on a single-speed cruiser, the simplest bike at the donation bay.",
    status: "planned",
  },
  {
    id: 2,
    season: 1,
    ep: 2,
    slug: "tires-tubes-flats",
    title: "Tires, Tubes, Flats",
    subtitle: "Tire change on a single-speed cruiser.",
    apronLevel: "green",
    body: "The most common bicycle service on Earth. We walk a tire change end to end on a single-speed — no derailleur cage to fight, no shift cable in the way. The cleanest possible introduction to the back wheel.",
    status: "planned",
  },
  {
    id: 3,
    season: 1,
    ep: 3,
    slug: "brakes",
    title: "Brakes",
    subtitle: "Pad alignment, cable tension, caliper centering.",
    apronLevel: "green",
    body: "The system that keeps your apprentices alive. Pad geometry, cable seating, the caliper-centering trick that nobody teaches in the YouTube tutorials.",
    status: "planned",
  },
  {
    id: 4,
    season: 1,
    ep: 4,
    slug: "drivetrain-basics",
    title: "Drivetrain Basics",
    subtitle: "Chain, sprocket, chain tension, lubrication.",
    apronLevel: "green",
    body: "Why a clean chain is a fast chain. The single-speed drivetrain in full: chainring, rear sprocket, chain tension at the dropouts, lubricant chemistry, chain stretch — the simplest possible drivetrain conversation, with everything that's true here still true on every bike that follows.",
    status: "planned",
  },
  {
    id: 5,
    season: 1,
    ep: 5,
    slug: "wheels-true-and-tension",
    title: "Wheels — True vs. Tension",
    subtitle: "Basic spoke replacement and the truing stand.",
    apronLevel: "red",
    body: "A wheel is a tensioned argument. Reading tension by ear, identifying the offending spoke, and the small adjustments that turn a rideable wheel into a true one.",
    status: "planned",
  },
  {
    id: 6,
    season: 1,
    ep: 6,
    slug: "bearings-and-headsets",
    title: "Bearings & Headsets",
    subtitle: "The friction story.",
    apronLevel: "red",
    body: "Every bearing is a contract between two surfaces. We service a headset on the cruiser and use it to tell the larger story of how friction is managed across the bike.",
    status: "planned",
  },
  {
    id: 7,
    season: 1,
    ep: 7,
    slug: "bike-fit-and-first-ride-safety",
    title: "Bike Fit & First-Ride Safety",
    subtitle: "Sizing, helmet, the parking-lot lap.",
    apronLevel: "red",
    body: "The handoff. How a mechanic sets up a bike for a rider who has never owned one — saddle height, brake reach, helmet fit, and the parking-lot lap that catches the things a stand can't.",
    status: "planned",
  },
  {
    id: 8,
    season: 1,
    ep: 8,
    slug: "earned-not-given",
    title: "Earned, Not Given",
    subtitle: "Synthesis — the apron as credential.",
    apronLevel: "red",
    body: "Season 1 close. The Green and Red Apron credentials are not certificates of completion — they are credentials of practice. We tell the YEET apprenticeship story and the bike-you-keep model that makes the apron mean what it means.",
    status: "planned",
  },

  // ---- Season 2 — Apron Advanced (Purple + Black) -----------------------------
  {
    id: 9,
    season: 2,
    ep: 9,
    slug: "wheel-building-and-truing",
    title: "Wheel Building & Truing",
    subtitle: "Lacing patterns, dish, the building bench.",
    apronLevel: "purple",
    body: "Build a wheel from a hub, a rim, and 32 spokes. The lacing math, the tensioning order, the dish gauge, and the satisfaction of riding a wheel you built.",
    status: "planned",
  },
  {
    id: 10,
    season: 2,
    ep: 10,
    slug: "bottom-brackets-and-cranks",
    title: "Bottom Brackets & Cranks",
    subtitle: "The pedal-power interface.",
    apronLevel: "purple",
    body: "Square taper, Octalink, ISIS, Hollowtech, BB30. A field guide to bottom-bracket archaeology, told through the case of a 1990s steel cruiser whose crankset needs replacing.",
    status: "planned",
  },
  {
    id: 11,
    season: 2,
    ep: 11,
    slug: "hubs-and-freewheels",
    title: "Hubs & Freewheels",
    subtitle: "Cassettes, freewheels, and the internal-hub sidebar.",
    apronLevel: "purple",
    body: "The cassette and freewheel world that powers multi-gear bikes. Plus the Sturmey-Archer and Shimano Nexus internal-hub bikes you'll also see at the shop — pawl geometry, oil intervals, and the disassembly nobody does until the hub fails.",
    status: "planned",
  },
  {
    id: 12,
    season: 2,
    ep: 12,
    slug: "shifting-systems",
    title: "Shifting Systems",
    subtitle: "Cable vs. internal hub, derailleur tuning.",
    apronLevel: "purple",
    body: "Indexing, cable stretch, B-screw geometry, internal-hub clicks. We tune a multi-gear bike's derailleur and a Sturmey internal hub side by side, and explain when each philosophy makes sense.",
    status: "planned",
  },
  {
    id: 13,
    season: 2,
    ep: 13,
    slug: "frame-assessment-and-alignment",
    title: "Frame Assessment & Alignment",
    subtitle: "Reading a frame for the truth it tells.",
    apronLevel: "black",
    body: "Dropout alignment, head-tube reaming, the dish of a rear triangle. How a master mechanic reads a frame's history without taking it apart.",
    status: "planned",
  },
  {
    id: 14,
    season: 2,
    ep: 14,
    slug: "suspension-and-dampers",
    title: "Suspension & Dampers",
    subtitle: "Forks, dampers, and where small wheels change the math.",
    apronLevel: "black",
    body: "Front-fork dampers on hybrids, full suspension on mountain bikes, and a forward-glance at the elastomer rear suspension we'll meet on the Brompton in Season 3 — why small-wheeled folders make different damping choices entirely.",
    status: "planned",
  },
  {
    id: 15,
    season: 2,
    ep: 15,
    slug: "restoration-triage",
    title: "Restoration Triage",
    subtitle: "The donation-bike pipeline.",
    apronLevel: "black",
    body: "A bike arrives at the shop. In thirty seconds you decide: parts donor, restorable, ridable today. The triage system that keeps the donation pipeline flowing.",
    status: "planned",
  },
  {
    id: 16,
    season: 2,
    ep: 16,
    slug: "the-black-apron",
    title: "The Black Apron",
    subtitle: "Synthesis — what mastery looks like.",
    apronLevel: "black",
    body: "Season 2 close. The Black Apron is taught by example, not earned by exam. We talk about what it means to be the most senior wrench in the room and how that responsibility hands itself off.",
    status: "planned",
  },

  // ---- Season 3 — Bike Design & Folding-Bike Engineering ----------------------
  {
    id: 17,
    season: 3,
    ep: 17,
    slug: "frame-geometry",
    title: "Frame Geometry",
    subtitle: "Head angle, trail, wheelbase.",
    apronLevel: "engineering",
    body: "After two seasons on cruisers and multi-gear bikes, we meet the Brompton. Why a Brompton handles like a Brompton — head angle, trail, wheelbase — and the relationship between numbers on paper and feel on a road.",
    status: "planned",
  },
  {
    id: 18,
    season: 3,
    ep: 18,
    slug: "the-hinge",
    title: "The Hinge",
    subtitle: "Load paths, fatigue, fifty years of one design.",
    apronLevel: "engineering",
    body: "Andrew Ritchie's hinge has not changed in the half-century since he sketched it. We follow the load path through the joint, explain why it doesn't fatigue, and why every other folder copied the principle.",
    status: "planned",
  },
  {
    id: 19,
    season: 3,
    ep: 19,
    slug: "wheels-small",
    title: "Wheels Small",
    subtitle: "16-inch engineering and gyroscopic feel.",
    apronLevel: "engineering",
    body: "Small wheels are not weakness. We unpack the gyroscopic and contact-patch math that makes a 16-inch folder ride the way it does — quicker steering, different braking dynamics, a different relationship to potholes.",
    status: "planned",
  },
  {
    id: 20,
    season: 3,
    ep: 20,
    slug: "drivetrain-on-a-folder",
    title: "Drivetrain on a Folder",
    subtitle: "Chain line, gear range, ratio math.",
    apronLevel: "engineering",
    body: "How do you fit a 6-speed range into a frame that folds? Internal-hub plus chainring math, chain-line constraints, and the elegant compromise the Brompton settled on.",
    status: "planned",
  },
  {
    id: 21,
    season: 3,
    ep: 21,
    slug: "materials-and-manufacturing",
    title: "Materials & Manufacturing",
    subtitle: "Steel vs. titanium vs. aluminum, brazing vs. welding.",
    apronLevel: "engineering",
    body: "The Brompton is brazed lugged steel. We tell the materials story across the folder market — why steel, why brazing, what changes when you switch to titanium or carbon, what a Brompton T-Line feels like in the hand.",
    status: "planned",
  },
  {
    id: 22,
    season: 3,
    ep: 22,
    slug: "the-fold",
    title: "The Fold",
    subtitle: "Patent history, taxonomies, why Brompton's won.",
    apronLevel: "engineering",
    body: "A short cultural history of the fold itself. Ritchie's 1975 design, Bickerton, Birdy, Strida, Tern — and why the Brompton fold survived the market's filter.",
    status: "planned",
  },
  {
    id: 23,
    season: 3,
    ep: 23,
    slug: "riding-the-city-on-a-folder",
    title: "Riding the City on a Folder",
    subtitle: "Multimodal transport, regulation, urban design.",
    apronLevel: "engineering",
    body: "A folder is the only bike that lets you walk into a meeting carrying it. We follow Indianapolis routes (Monon Trail, White River Greenway, Cultural Trail) and explain how the fold rewrites multimodal commuting.",
    status: "planned",
  },
  {
    id: 24,
    season: 3,
    ep: 24,
    slug: "designed-to-disappear",
    title: "Designed to Disappear",
    subtitle: "Synthesis — a folder is the only bike that lives in your kitchen.",
    apronLevel: "engineering",
    body: "Season 3 close. The whole point of a folder is that it stops being a bike when you're not riding it. The design implications, the cultural implications, the reason Brompton built a brand on a kitchen-table object.",
    status: "planned",
  },

  // ---- Season 4 — Program Operations & Community ------------------------------
  {
    id: 25,
    season: 4,
    ep: 25,
    slug: "running-a-class",
    title: "Running a Class",
    subtitle: "Pedagogy for hands-on tool work.",
    apronLevel: "community",
    body: "How do you teach a tool? You don't lecture; you sequence. The pedagogy of a hands-on shop class — reading the room, scaffolding the demo, knowing when to step back.",
    status: "planned",
  },
  {
    id: 26,
    season: 4,
    ep: 26,
    slug: "the-bike-lab",
    title: "The Bike Lab",
    subtitle: "Open shop dynamics and volunteer management.",
    apronLevel: "community",
    body: "The hardest classroom is the one with no syllabus. Open-shop nights, rotating volunteers, the riders who walk in mid-repair — and the systems that keep the Bike Lab running.",
    status: "planned",
  },
  {
    id: 27,
    season: 4,
    ep: 27,
    slug: "community-bike-rides",
    title: "Community Bike Rides",
    subtitle: "Route design, sweep riders, family inclusion.",
    apronLevel: "community",
    body: "A monthly ride is not a tour — it's a recruitment funnel and a wellness intervention. Route design, sweep-rider protocol, and how to make a ride family-shaped.",
    status: "planned",
  },
  {
    id: 28,
    season: 4,
    ep: 28,
    slug: "yeet-the-apprenticeship",
    title: "YEET — The Apprenticeship",
    subtitle: "Youth employment training, timesheets, the first paycheck.",
    apronLevel: "community",
    body: "YEET is FreeWheelin's youth-apprenticeship program. We walk through what it takes to run it — timesheets, payroll, the supervisor cadence — and what it means to a fifteen-year-old's first W-2.",
    status: "planned",
  },
  {
    id: 29,
    season: 4,
    ep: 29,
    slug: "donation-days-and-fundraising",
    title: "Donation Days & Fundraising",
    subtitle: "The Annual Fund Coordinator's view.",
    apronLevel: "community",
    body: "Donation days, garage sales, the spring fundraiser. The unglamorous half of a non-profit's calendar — and why those days are where the year's program budget gets made.",
    status: "planned",
  },
  {
    id: 30,
    season: 4,
    ep: 30,
    slug: "partnerships-and-outreach",
    title: "Partnerships & Outreach",
    subtitle: "The Director of Programs lens.",
    apronLevel: "community",
    body: "How does a community bike shop find its next class of apprentices? Partnership development, school relationships, the outreach calendar that fills a roster.",
    status: "planned",
  },
  {
    id: 31,
    season: 4,
    ep: 31,
    slug: "data-reporting-grants",
    title: "Data, Reporting, Grants",
    subtitle: "The Administrative Support Coordinator's view.",
    apronLevel: "community",
    body: "Grants don't ask for stories — they ask for numbers. Attendance, completion, bikes earned, post-program outcomes. The reporting cadence that makes a program fundable.",
    status: "planned",
  },
  {
    id: 32,
    season: 4,
    ep: 32,
    slug: "the-full-wheel",
    title: "The Full Wheel",
    subtitle: "Synthesis — Indianapolis, the bike, the kid, the apron.",
    apronLevel: "community",
    isHome: true,
    body: "The series close. We bring all four seasons home to Indianapolis — one bike, one curriculum, one kid in a green apron earning the bike they'll ride out of the shop. Now that you know — what will you do with it?",
    status: "planned",
  },
];

export function episodeBySlug(slug: string): Episode | undefined {
  return EPISODES.find((e) => e.slug === slug);
}

export function episodesBySeason(season: number): Episode[] {
  return EPISODES.filter((e) => e.season === season);
}
